### ISSUE TITLE
Add option to appy currently "forbidden labels" to nodes

### ISSUE THREAD

**Issue by Zeka13** [banzaicloud/nodepool-labels-operator#14]
Hello. I was happy to find this repo, because I want to apply label which exclude node from Azure Load Balancer automatically

And I am able to do this with kubectl

```
kubectl label nodes k8s-consolidated-my-node-name node.kubernetes.io/exclude-from-external-load-balancers=true
``` 

But when I do the same with nodepool-labels-operator operator I get 

**msg="forbidden label" label=node.kubernetes.io/exclude-from-external-load-balancers labelValue=true node=k8s-consolidated-some-node-name**

```
apiVersion: labels.banzaicloud.io/v1alpha1
kind: NodePoolLabelSet
metadata:
  name: consolidated
spec:
  labels:
    node.kubernetes.io/exclude-from-external-load-balancers: "true"
```

I only can guess this is happening because of lable name start with **node.kubernetes.io/**, but I don't understand what the problem with it and is there a way to avoid it?

**Thx in advance**

**Comment by Zeka13** [comment]
NVM I found there is a way to configure this via helm values
```
configuration:
  labeler:
    forbiddenLabelDomains:
      - "k8s.io"
      - "google.com"
```
