### ISSUE TITLE
NodePoolLabelSet always use default namespace 

### ISSUE THREAD

**Issue by Links2004** [banzaicloud/nodepool-labels-operator#26]
**Describe the bug**
we want to deploy the controller in the `kube-system` name, but it always use the `NodePoolLabelSet` from the `default` ns.

**Steps to reproduce the issue:**
  config.yaml
```yaml
    controller:
      namespace: kube-system
      nodepoolNameLabels:
      - nodepool.banzaicloud.io/name
      - kubernetes.io/hostname
    labeler:
      forbiddenLabelDomains:
      - google.com
      managedLabelsAnnotation: nodepool.banzaicloud.io/managed-labels
    log:
      format: logfmt
      level: debug
    healthcheck:
      listenAddress: ":8882"
      endpoint: "/healthz"
```

broken:
```yaml
---
apiVersion: labels.banzaicloud.io/v1alpha1
kind: NodePoolLabelSet
metadata:
  name: test-host
  namespace: kube-system
spec:
  labels:
    test-label2: "test-value2"
```

working:
```yaml
---
apiVersion: labels.banzaicloud.io/v1alpha1
kind: NodePoolLabelSet
metadata:
  name: test-host
  namespace: default
spec:
  labels:
    test-label2: "test-value2"
```

**Expected behavior**
`NodePoolLabelSet` is working in namespaces
